services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb
    image: mariadb:notlatest
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
      - ../secrets/db_password.txt:/run/secrets/db_password.txt:ro
      - ../secrets/db_root_password.txt:/run/secrets/db_root_password.txt:ro
    restart: always
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    image: nginx:notlatest
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: always
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress:notlatest
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
      - ../secrets/wp_password.txt:/run/secrets/wp_password.txt:ro
      - ../secrets/wp_admin_password.txt:/run/secrets/wp_admin_password.txt:ro
      - ../secrets/db_password.txt:/run/secrets/db_password.txt:ro
    restart: always
    expose:
      - "9000"

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/smoore-a/InceptionData/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/smoore-a/InceptionData/wordpress
      o: bind

networks:
  inception:
    name: inception
    driver: bridge
